// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfO4k8YvBhIP4_gdCLdcHtPMOWpHRCKS8',
    appId: '1:128782564126:web:62d82fe49c4c101149670f',
    messagingSenderId: '128782564126',
    projectId: 'voting-app-9c86d',
    authDomain: 'voting-app-9c86d.firebaseapp.com',
    storageBucket: 'voting-app-9c86d.appspot.com',
    measurementId: 'G-51MXW0NVCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuaW0BiyYdNlZRV14o15tVh5jirHf15CU',
    appId: '1:128782564126:android:f91da5627226759749670f',
    messagingSenderId: '128782564126',
    projectId: 'voting-app-9c86d',
    storageBucket: 'voting-app-9c86d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUFm26m2jPizJv1BdlZA8LaPXKbAVMx00',
    appId: '1:128782564126:ios:3bf92322ac58820a49670f',
    messagingSenderId: '128782564126',
    projectId: 'voting-app-9c86d',
    storageBucket: 'voting-app-9c86d.appspot.com',
    iosBundleId: 'com.example.votingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUFm26m2jPizJv1BdlZA8LaPXKbAVMx00',
    appId: '1:128782564126:ios:3bf92322ac58820a49670f',
    messagingSenderId: '128782564126',
    projectId: 'voting-app-9c86d',
    storageBucket: 'voting-app-9c86d.appspot.com',
    iosBundleId: 'com.example.votingApp',
  );
}
